name: GHAction example_dodatkowe

on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'

jobs:
  ci_step:
    name: Build, tag, push, and scan Docker image
    runs-on: ubuntu-latest
      
    steps:
      - name: Check out the source_repo
        uses: actions/checkout@v4
      
      - name: Docker metadata definitions
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKERHUB_USERNAME }}/example
          flavor: latest=false
          tags: |
            type=sha,priority=100,prefix=sha-,format=short
            type=semver,priority=200,pattern={{version}}   

      - name: QEMU set-up
        uses: docker/setup-qemu-action@v3

      - name: Buildx set-up
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: |
            type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/example:cache 
          cache-to: |
            type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/example:cache  
          tags: ${{ steps.meta.outputs.tags }}
          
      - name: Generate SBOM with Syft
        uses: anchore/syft-action@v1
        with:
          image: ${{ vars.DOCKERHUB_USERNAME }}/example:${{ steps.meta.outputs.tags }}
          format: spdx-json
          output-file: sbom.json

      - name: Attach SBOM to Provenance
        run: |
          echo "Attaching SBOM to provenance (example step)"
          # Placeholder for attaching SBOM to provenance

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v0.11.0
        with:
          image-ref: ${{ vars.DOCKERHUB_USERNAME }}/example:${{ steps.meta.outputs.tags }}
          severity: HIGH,CRITICAL
          format: table
          exit-code: 1

      - name: Upload SBOM and scan results as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: scan-and-sbom-results
          path: |
            sbom.json
            trivy-report.txt